### ISSUE TITLE
KeyError: 'data'

### ISSUE THREAD

**Issue by e-lunev** [luanon404/Quizizz-Cheat#2]
Traceback (most recent call last):
  File "C:\Users\Jenya\Desktop\qwizizz.py", line 259, in <module>
    answers = quizizz.get_right_answer(room_hash)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jenya\Desktop\qwizizz.py", line 156, in get_right_answer
    for question in resp.json()["data"]["questions"]:
                    ~~~~~~~~~~~^^^^^^^^
KeyError: 'data'

**Comment by luanon404** [comment]
i fixed that, pls recheck my code
